[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/pio_select_port.py
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:bubu]
build_flags = ${env.build_flags} -DDEVICE_BUBU
custom_device_mac = E8:F6:0A:12:4C:A4

[env:dudu]
build_flags = ${env.build_flags} -DDEVICE_DUDU
custom_device_mac = E8:F6:0A:12:5B:84