[platformio]
extra_configs = .pio/ports.ini

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel
extra_scripts = pre:tools/pio_select_port.py
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:bubu]
custom_device_mac = E8:F6:0A:12:4C:A4
build_flags = ${env.build_flags} -DDEVICE_BUBU

[env:dudu]
custom_device_mac = E8:F6:0A:12:5B:84
build_flags = ${env.build_flags} -DDEVICE_DUDU