# Runs inside PlatformIO's own Python (penv) as an extra_script -> pyserial is available.
import os, re, shutil, signal, subprocess, sys, time
from serial.tools import list_ports
from SCons.Script import COMMAND_LINE_TARGETS

Import("env")

ESPRESSIF_VID = 0x303A
UPLOAD_TARGETS = {"upload", "uploadfs", "uploadfsota"}
PORTS_INI = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "ports.ini")
MAIN_INI = os.path.join(env.subst("$PROJECT_DIR"), "platformio.ini")


def log(msg):
    print(f"[select_port] {msg}")


def fail(msg):
    sys.stderr.write(f"\n[select_port] ERROR: {msg}\n\n")
    env.Exit(1)


def norm(mac):
    """Accepts 'e8-f6-0a-12-4c-a4', 'E8F60A124CA4', ... -> 'E8:F6:0A:12:4C:A4' ('' if not a MAC)."""
    h = re.sub(r"[^0-9A-Fa-f]", "", mac or "").upper()
    return ":".join(h[i:i + 2] for i in range(0, 12, 2)) if len(h) == 12 else ""


def expected_mac():
    mac = norm(env.GetProjectOption("custom_device_mac", ""))
    if not mac:
        fail(f"custom_device_mac missing or invalid for env '{env['PIOENV']}'")
    return mac


def espressif_ports():
    return sorted(
        (p for p in list_ports.comports()
         if p.vid == ESPRESSIF_VID and p.device.startswith("/dev/cu.")),
        key=lambda p: p.device)


def wait_for_port(port, timeout=5.0):
    t0 = time.time()
    while time.time() - t0 < timeout:
        if os.path.exists(port):
            return True
        time.sleep(0.2)
    return False


def read_mac_with_esptool(port):
    """Fallback only. Resets that one board."""
    esptool_dir = env.PioPlatform().get_package_dir("tool-esptoolpy")
    cmd = [env.subst("$PYTHONEXE"), os.path.join(esptool_dir, "esptool.py"),
           "--chip", "esp32c3", "--port", port, "--no-stub",
           "--before", "default_reset", "--after", "hard_reset", "read_mac"]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=20).stdout
    except subprocess.TimeoutExpired:
        return ""
    m = re.search(r"^MAC:\s*([0-9A-Fa-f:]{17})", out, re.M)
    wait_for_port(port)
    return norm(m.group(1)) if m else ""


def find_port(expected):
    ports = espressif_ports()
    if not ports:
        fail("No Espressif USB devices connected.")

    # 1) Fast path: macOS exposes the ESP32 MAC as the USB serial number.
    matches = [p.device for p in ports if norm(p.serial_number) == expected]
    if len(matches) > 1:
        fail(f"MAC {expected} appears on several ports: {', '.join(matches)}")
    if matches:
        return matches[0]

    # 2) Fallback: only probe ports that expose NO serial number (never resets a known board).
    for p in ports:
        if norm(p.serial_number):
            continue
        log(f"{p.device} has no USB serial number; probing with esptool (resets that board) ...")
        if read_mac_with_esptool(p.device) == expected:
            return p.device

    seen = ", ".join(f"{p.device} (SER={p.serial_number})" for p in ports)
    fail(f"No connected board has MAC {expected} (env '{env['PIOENV']}'). Seen: {seen}")


def port_holders(port):
    """Text listing processes that currently have `port` open, or '' if free / unknown."""
    if not shutil.which("lsof"):
        return ""
    try:
        r = subprocess.run(["lsof", "-w", port], capture_output=True, text=True, timeout=10)
    except subprocess.TimeoutExpired:
        return ""
    return r.stdout.strip() if r.returncode == 0 else ""


def ensure_free(port, name):
    who = port_holders(port)
    if who:
        fail(f"{name}'s port {port} is busy. Close the other monitor/terminal first.\n"
             f"Held by:\n{who}")


def write_ports_file():
    """Write each board's current port to .pio/ports.ini so the BUILT-IN
    Monitor button opens the right board. Uses USB serial numbers only (no resets)."""
    config = env.GetProjectConfig()
    ports = espressif_ports()
    lines = ["; AUTO-GENERATED by tools/pio_select_port.py - do not edit"]
    for e in config.envs():
        mac = norm(config.get(f"env:{e}", "custom_device_mac", ""))
        if not mac:
            continue
        match = [p.device for p in ports if norm(p.serial_number) == mac]
        if len(match) == 1:
            lines += [f"[env:{e}]", f"monitor_port = {match[0]}"]
            config.set(f"env:{e}", "monitor_port", match[0])  # for Upload+Monitor in this same run
    content = "\n".join(lines) + "\n"
    old = open(PORTS_INI).read() if os.path.exists(PORTS_INI) else ""
    if content != old:
        os.makedirs(os.path.dirname(PORTS_INI), exist_ok=True)
        with open(PORTS_INI, "w") as f:
            f.write(content)
        log(f"updated {PORTS_INI}")


write_ports_file()


# ---- Upload: resolve the port before the upload step runs ----
if set(COMMAND_LINE_TARGETS) & UPLOAD_TARGETS:
    if env.GetProjectOption("upload_port", None):
        fail("Remove upload_port from platformio.ini; ports are resolved by MAC.")
    expected = expected_mac()
    port = find_port(expected)
    ensure_free(port, env["PIOENV"])
    log(f"upload: env '{env['PIOENV']}' ({expected}) -> {port}")
    env.Replace(UPLOAD_PORT=port)

# ---- Monitor: custom target, runs inside SCons so this script can pick the port ----
def monitor_task(*_, **__):
    expected = expected_mac()
    port = find_port(expected)
    ensure_free(port, env["PIOENV"])
    speed = str(env.GetProjectOption("monitor_speed", "115200"))
    log(f"monitor: env '{env['PIOENV']}' ({expected}) -> {port} @ {speed}")
    cmd = [env.subst("$PYTHONEXE"), "-m", "platformio", "device", "monitor",
           "--environment", env["PIOENV"], "--port", port, "--baud", speed]
    # Let Ctrl+C go to the monitor (which quits cleanly), not to SCons.
    old = signal.signal(signal.SIGINT, signal.SIG_IGN)
    try:
        return subprocess.call(
            cmd, preexec_fn=lambda: signal.signal(signal.SIGINT, signal.SIG_DFL))
    finally:
        signal.signal(signal.SIGINT, old)


env.AddCustomTarget(
    "monitor_auto", None, monitor_task,
    title=f"Monitor {env['PIOENV']} (auto port)",
    description="Find this board by MAC (USB serial number), then open only its port")